// Generated by scripts/refresh-artefacts.mjs. Do not edit by hand.

import context_vcdm_2_credentials from './artefacts/context/vcdm/2/credentials.js';
import schema_vcdm_2_verifiable_credential from './artefacts/schema/vcdm/2/verifiable-credential.js';
import schema_untp_0_7_0_dpp from './artefacts/schema/untp/0.7.0/dpp.js';
import schema_untp_0_7_0_dcc from './artefacts/schema/untp/0.7.0/dcc.js';
import schema_untp_0_7_0_dfr from './artefacts/schema/untp/0.7.0/dfr.js';
import schema_untp_0_7_0_dia from './artefacts/schema/untp/0.7.0/dia.js';
import schema_untp_0_7_0_dte from './artefacts/schema/untp/0.7.0/dte.js';
import schema_untp_0_7_0_cvc from './artefacts/schema/untp/0.7.0/cvc.js';
import schema_untp_0_7_0_linkset from './artefacts/schema/untp/0.7.0/linkset.js';
import context_untp_0_7_0_untp from './artefacts/context/untp/0.7.0/untp.js';
import schema_untp_0_6_0_dpp from './artefacts/schema/untp/0.6.0/dpp.js';
import context_untp_0_6_0_dpp from './artefacts/context/untp/0.6.0/dpp.js';
import schema_untp_0_6_0_dcc from './artefacts/schema/untp/0.6.0/dcc.js';
import context_untp_0_6_0_dcc from './artefacts/context/untp/0.6.0/dcc.js';
import schema_untp_0_6_0_dfr from './artefacts/schema/untp/0.6.0/dfr.js';
import context_untp_0_6_0_dfr from './artefacts/context/untp/0.6.0/dfr.js';
import schema_untp_0_6_0_dia from './artefacts/schema/untp/0.6.0/dia.js';
import context_untp_0_6_0_dia from './artefacts/context/untp/0.6.0/dia.js';
import schema_untp_0_6_0_dte from './artefacts/schema/untp/0.6.0/dte.js';
import context_untp_0_6_0_dte from './artefacts/context/untp/0.6.0/dte.js';
import schema_untp_0_6_1_dpp from './artefacts/schema/untp/0.6.1/dpp.js';
import context_untp_0_6_1_dpp from './artefacts/context/untp/0.6.1/dpp.js';
import schema_untp_0_6_1_dcc from './artefacts/schema/untp/0.6.1/dcc.js';
import context_untp_0_6_1_dcc from './artefacts/context/untp/0.6.1/dcc.js';
import schema_untp_0_6_1_dfr from './artefacts/schema/untp/0.6.1/dfr.js';
import context_untp_0_6_1_dfr from './artefacts/context/untp/0.6.1/dfr.js';
import schema_untp_0_6_1_dia from './artefacts/schema/untp/0.6.1/dia.js';
import context_untp_0_6_1_dia from './artefacts/context/untp/0.6.1/dia.js';
import schema_untp_0_6_1_dte from './artefacts/schema/untp/0.6.1/dte.js';
import context_untp_0_6_1_dte from './artefacts/context/untp/0.6.1/dte.js';

/** Bundled artefacts keyed by the published URL consumers request. */
export const BUNDLED_ARTEFACTS: ReadonlyMap<string, object> = new Map<string, object>([
  ['https://www.w3.org/ns/credentials/v2', context_vcdm_2_credentials],
  [
    'https://w3c.github.io/vc-data-model/schema/verifiable-credential/verifiable-credential-schema.json',
    schema_vcdm_2_verifiable_credential,
  ],
  ['https://untp.unece.org/artefacts/schema/v0.7.0/dpp/DigitalProductPassport.json', schema_untp_0_7_0_dpp],
  ['https://untp.unece.org/artefacts/schema/v0.7.0/dcc/ConformityCredential.json', schema_untp_0_7_0_dcc],
  ['https://untp.unece.org/artefacts/schema/v0.7.0/dfr/DigitalFacilityRecord.json', schema_untp_0_7_0_dfr],
  ['https://untp.unece.org/artefacts/schema/v0.7.0/dia/DigitalIdentityAnchor.json', schema_untp_0_7_0_dia],
  ['https://untp.unece.org/artefacts/schema/v0.7.0/dte/DigitalTraceabilityEvent.json', schema_untp_0_7_0_dte],
  ['https://untp.unece.org/artefacts/schema/v0.7.0/cvc/ConformityScheme.json', schema_untp_0_7_0_cvc],
  ['https://untp.unece.org/artefacts/schema/v0.7.0/idr/LinksetSchema.json', schema_untp_0_7_0_linkset],
  ['https://vocabulary.uncefact.org/untp/0.7.0/context/', context_untp_0_7_0_untp],
  ['https://test.uncefact.org/vocabulary/untp/dpp/untp-dpp-schema-0.6.0.json', schema_untp_0_6_0_dpp],
  ['https://test.uncefact.org/vocabulary/untp/dpp/0.6.0/context/', context_untp_0_6_0_dpp],
  ['https://test.uncefact.org/vocabulary/untp/dcc/untp-dcc-schema-0.6.0.json', schema_untp_0_6_0_dcc],
  ['https://test.uncefact.org/vocabulary/untp/dcc/0.6.0/context/', context_untp_0_6_0_dcc],
  ['https://test.uncefact.org/vocabulary/untp/dfr/untp-dfr-schema-0.6.0.json', schema_untp_0_6_0_dfr],
  ['https://test.uncefact.org/vocabulary/untp/dfr/0.6.0/context/', context_untp_0_6_0_dfr],
  ['https://test.uncefact.org/vocabulary/untp/dia/untp-dia-schema-0.6.0.json', schema_untp_0_6_0_dia],
  ['https://test.uncefact.org/vocabulary/untp/dia/0.6.0/context/', context_untp_0_6_0_dia],
  ['https://test.uncefact.org/vocabulary/untp/dte/untp-dte-schema-0.6.0.json', schema_untp_0_6_0_dte],
  ['https://test.uncefact.org/vocabulary/untp/dte/0.6.0/context/', context_untp_0_6_0_dte],
  ['https://test.uncefact.org/vocabulary/untp/dpp/untp-dpp-schema-0.6.1.json', schema_untp_0_6_1_dpp],
  ['https://test.uncefact.org/vocabulary/untp/dpp/0.6.1/context/', context_untp_0_6_1_dpp],
  ['https://test.uncefact.org/vocabulary/untp/dcc/untp-dcc-schema-0.6.1.json', schema_untp_0_6_1_dcc],
  ['https://test.uncefact.org/vocabulary/untp/dcc/0.6.1/context/', context_untp_0_6_1_dcc],
  ['https://test.uncefact.org/vocabulary/untp/dfr/untp-dfr-schema-0.6.1.json', schema_untp_0_6_1_dfr],
  ['https://test.uncefact.org/vocabulary/untp/dfr/0.6.1/context/', context_untp_0_6_1_dfr],
  ['https://test.uncefact.org/vocabulary/untp/dia/untp-dia-schema-0.6.1.json', schema_untp_0_6_1_dia],
  ['https://test.uncefact.org/vocabulary/untp/dia/0.6.1/context/', context_untp_0_6_1_dia],
  ['https://test.uncefact.org/vocabulary/untp/dte/untp-dte-schema-0.6.1.json', schema_untp_0_6_1_dte],
  ['https://test.uncefact.org/vocabulary/untp/dte/0.6.1/context/', context_untp_0_6_1_dte],
]);

/** UNTP versions the bundle carries, ascending. */
export const BUNDLED_UNTP_VERSIONS: readonly string[] = ['0.6.0', '0.6.1', '0.7.0'];
